version: '3.9'

services:
  nextcloud-db:
    image: mariadb:latest
    container_name: nextcloud-db
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - /storage/appdata/gold/nextcloud-db:/var/lib/mysql
    env_file:
      - nextcloud.env

  nextcloud-redis:
    image: redis
    restart: always

  nextcloud-app:
    build: ./nextcloud
    restart: always
    ports:
      - 5234:80
    volumes:
      - /storage/appdata/gold/nextcloud/html:/var/www/html
    environment:
      - MYSQL_HOST=nextcloud-db
    env_file:
      - nextcloud.env
    depends_on:
      - nextcloud-db
      - nextcloud-redis

  nextcloud-cron:
    build: ./nextcloud
    restart: always
    volumes:
      - /storage/appdata/gold/nextcloud/html:/var/www/html
    entrypoint: /cron.sh
    depends_on:
      - nextcloud-db
      - nextcloud-redis
