services:
  commafeed:
    image: athou/commafeed:latest-postgresql
    container_name: commafeed
    restart: unless-stopped
    environment:
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://commafeed-postgresql:5432/commafeed
      - QUARKUS_DATASOURCE_USERNAME=commafeed
      - QUARKUS_DATASOURCE_PASSWORD=commafeed
      - COMMAFEED_USERS_ALLOW_REGISTRATIONS=false
    deploy:
      resources:
        limits:
          memory: 256M
    ports:
      - 8086:8082

  commafeed-postgresql:
    image: postgres:latest
    container_name: commafeed-postgresql
    restart: unless-stopped
    environment:
      POSTGRES_USER: commafeed
      POSTGRES_PASSWORD: commafeed
      POSTGRES_DB: commafeed
    volumes:
      - /storage/appdata/bronze/commafeed-postgresql:/var/lib/postgresql/data
