version: '3.9'

services:
  nextcloud-app:
    build: ./nextcloud
    container_name: nextcloud-app
    restart: always
    ports:
      - 5234:80
    volumes:
      - /storage/appdata/gold/nextcloud/html:/var/www/html
      - /storage/appdata/gold/nextcloud/html/data:/var/www/html/data
    environment:
      - MYSQL_HOST=nextcloud-db
    env_file:
      - nextcloud.env
    depends_on:
      - nextcloud-db
      - nextcloud-redis
    networks:
      - default
      - nextcloud_private

  nextcloud-db:
    image: mariadb:latest
    container_name: nextcloud-db
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - /storage/appdata/gold/nextcloud-db:/var/lib/mysql
    env_file:
      - nextcloud.env
    networks:
      - nextcloud_private

  nextcloud-redis:
    image: redis
    container_name: nextcloud-redis
    restart: always
    networks:
      - nextcloud_private

  nextcloud-cron:
    build: ./nextcloud
    container_name: nextcloud-cron
    restart: always
    volumes:
      - /storage/appdata/gold/nextcloud/html:/var/www/html
    entrypoint: /cron.sh
    depends_on:
      - nextcloud-db
      - nextcloud-redis
    networks:
      - nextcloud_private

networks:
  nextcloud_private:
    driver: bridge