version: '3.9'

services:

  nextcloud:
    image: nextcloud:latest
    container_name: nextcloud
    restart: always
    depends_on:
      - nextcloud-db
    environment:
      - MYSQL_PASSWORD=nextcloud
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=nextcloud-db
      - TRUSTED_DOMAINS=cloud.anarchy.pizza
      - OVERWRITEPROTOCOL=https
      - OVERWRITEHOST=cloud.anarchy.pizza
      - TRUSTED_PROXIES=172.29.0.7,192.168.86.100
    volumes:
      - /storage/appdata/gold/nextcloud/html:/var/www/html
      - /storage/appdata/gold/nextcloud/data:/var/www/html/data

  nextcloud-db:
    image: mariadb:latest
    container_name: nextcloud-db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=nextcloud
      - MYSQL_PASSWORD=nextcloud
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    volumes:
      - /storage/appdata/gold/nextcloud-db:/var/lib/mysql\
    networks:
      default:
        aliases:
          - nextcloud-db
