version: '3.8'

services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    restart: unless-stopped
    ports:
      - "8096:8096" # Change port if needed
    volumes:
      - ./config:/config
      - ./cache:/cache
      - /path/to/media:/media # Update this to your actual media directory
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${LOCAL_TIMEZONE} # Change to your timezone
