version: "3.8"

services:
  blog:
    image: anarchy-pizza-blog:latest
    container_name: blog
    restart: always
    networks:
      - anarchy-pizzay

networks:
  anarchy-pizza:
    external:
      name: anarchy-pizza