services:
  calibre-web:
    image: lscr.io/linuxserver/calibre-web:0.6.27-ls397
    container_name: calibre-web
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=America/Denver
      - DOCKER_MODS=linuxserver/mods:universal-calibre #optional
      - OAUTHLIB_RELAX_TOKEN_SCOPE=1 #optional
    volumes:
      - ${STORAGE_ROOT}/bronze/calibre-web:/config
      - ${MEDIA_ROOT}/books:/books
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.calibreweb.rule=Host(`library.${DOMAIN}`)
      - traefik.http.routers.calibreweb.entrypoints=web
      - traefik.http.routers.calibreweb.middlewares=authelia@docker
      - traefik.http.services.calibreweb.loadbalancer.server.port=8083
      - traefik.http.routers.calibreweb-secure.rule=Host(`library.${DOMAIN}`)
      - traefik.http.routers.calibreweb-secure.entrypoints=websecure
      - traefik.http.routers.calibreweb-secure.tls.certresolver=le
      - traefik.http.routers.calibreweb-secure.service=calibreweb
      - traefik.http.routers.calibreweb-secure.middlewares=authelia@docker
    networks:
      - homelab

networks:
  homelab:
    name: homelab
    external: true