version: "3"
services:
  dozzle:
    container_name: dozzle
    image: amir20/dozzle:v10.7.3
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.dozzle.rule=Host(`dozzle.${DOMAIN}`)
      - traefik.http.routers.dozzle.entrypoints=web
      - traefik.http.routers.dozzle.middlewares=authelia@docker
      - traefik.http.services.dozzle.loadbalancer.server.port=8080
      - traefik.http.routers.dozzle-secure.rule=Host(`dozzle.${DOMAIN}`)
      - traefik.http.routers.dozzle-secure.entrypoints=websecure
      - traefik.http.routers.dozzle-secure.tls.certresolver=le
      - traefik.http.routers.dozzle-secure.service=dozzle
      - traefik.http.routers.dozzle-secure.middlewares=authelia@docker
    networks:
      - homelab

networks:
  homelab:
    external: true
