version: "3"
services:
  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.dozzle.rule=Host(`dozzle.${DOMAIN}`)
      - traefik.http.routers.dozzle.entrypoints=web
      - traefik.http.routers.dozzle.middlewares=authelia@docker
      - traefik.http.services.dozzle.loadbalancer.server.port=8080
    networks:
      - anarchy-pizza

networks:
  anarchy-pizza:
    external: true
