services:
  bandcampsync:
    image: ghcr.io/meeb/bandcampsync:latest
    container_name: bandcampsync
    restart: unless-stopped
    volumes:
      - ${STORAGE_ROOT}/bronze/bandcampsync:/config
      - ${MEDIA_ROOT}/music:/downloads
    environment:
      - TZ=America/Denver
      - PUID=${PUID}
      - PGID=${PGID}
      - RUN_DAILY_AT=1
    networks:
      - homelab

networks:
  homelab:
    name: homelab
    external: true