services:
  uptime-kuma:
    image: louislam/uptime-kuma:2
    restart: unless-stopped
    volumes:
      - ${STORAGE_ROOT}/bronze/uptime-kuma:/app/data
    labels:
      - traefik.enable=true
      - traefik.http.routers.uptimekuma.rule=Host(`uptime.${DOMAIN}`)
      - traefik.http.routers.uptimekuma.entrypoints=web
      - traefik.http.routers.uptimekuma.middlewares=authelia@docker
      - traefik.http.services.uptimekuma.loadbalancer.server.port=3001
      - traefik.http.routers.uptimekuma-secure.rule=Host(`uptime.${DOMAIN}`)
      - traefik.http.routers.uptimekuma-secure.entrypoints=websecure
      - traefik.http.routers.uptimekuma-secure.tls.certresolver=le
      - traefik.http.routers.uptimekuma-secure.service=uptimekuma
      - traefik.http.routers.uptimekuma-secure.middlewares=authelia@docker
    deploy:
      resources:
        limits:
          memory: 512M
    networks:
      - anarchy-pizza

networks:
  anarchy-pizza:
    name: anarchy-pizza
    external: true

