---
version: "3.8"
services:
  dashy:
    image: lissy93/dashy
    container_name: Dashy
    # Pass in your config file below, by specifying the path on your host machine
    volumes:
      - /storage/appdata/silver/dashy/conf.yml:/app/user-data/conf.yml
    ports:
      - 8080:8080
    # Set any environmental variables
    environment:
      - NODE_ENV=production
      - UID=1000
      - GID=1000
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'node', '/app/services/healthcheck']
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - anarchy-pizza

networks:
  anarchy-pizza:
    external:
      name: anarchy-pizza