services:

  traefik:
    image: traefik:latest
    container_name: traefik
    restart: unless-stopped
    command:
      - --providers.docker=true
      - --providers.docker.exposedByDefault=false
      - --providers.docker.network=anarchy-pizza
      - --entrypoints.web.address=:8080
      - --entrypoints.web.forwardedHeaders.trustedIPs=172.25.0.0/16
      - --log.level=INFO
    environment:
      - TZ=${TZ}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    deploy:
      resources:
        limits:
          memory: 256M
    networks:
      - anarchy-pizza

networks:
  anarchy-pizza:
    name: anarchy-pizza
    external: true
