version: '3.9'
services:
  filebrowser:
    image: filebrowser/filebrowser
    container_name: filebrowser
    restart: unless-stopped
    ports:
      - '8080:80'
    volumes:
      - /storage/silver/filebrowser/.database.db:/.database.db
      - /storage:/srv
    networks:
      - anarchy-pizza

networks:
  anarchy-pizza:
    external:
      name: anarchy-pizza
