version: "3.8"

services:
  otterwiki:
    image: redimp/otterwiki:2
    restart: unless-stopped
    volumes:
      - /storage/appdata/gold/otterwiki:/app-data

networks:
  anarchy-pizza:
    external:
      name: anarchy-pizza