version: '3.9'
services:
  open-webui:
    image: 'ghcr.io/open-webui/open-webui:ollama'
    container_name: open-webui
    restart: unless-stopped
    volumes:
      - '/storage/appdata/silver/open-webui:/app/backend/data'
      - '/storage/appdata/bronze/ollama:/root/.ollama'
    networks:
      - anarchy-pizza
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

networks:
        anarchy-pizza:
          external: true