version: "3.8"
services:
  
  npm:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: npm
    restart: unless-stopped
    ports:
      - "80:80"    # HTTP
      - "443:443"  # HTTPS
      - "81:81"    # NPM Web Interface
    volumes:
      - /storage/appdata/silver/nginx-proxy-manager:/data
      - /etc/letsencrypt:/etc/letsencrypt
    environment:
      - TZ=America/Denver
    networks:
      - anarchy-pizza

networks:
  anarchy-pizza:
    external:
      name: anarchy-pizza