version: "3.8"

services:
  gitea-db:
    image: mysql:8
    container_name: gitea-db
    restart: unless-stopped
    volumes:
      - /storage/appdata/gold/gitea-db:/var/lib/mysql
    env_file:
      - .env
    networks:
      - private

  gitea:
    image: gitea/gitea:latest
    container_name: gitea
    restart: unless-stopped
    depends_on:
      - gitea-db
    volumes:
      - /storage/appdata/gold/gitea:/data
    networks:
      - private
      - anarchy-pizza
    env_file:
      - .env
    ports:
      - 3000:3000

networks:
  anarchy-pizza:
    external:
      name: anarchy-pizza
  private:
    driver: bridge
